### ISSUE TITLE
Consulta EJ 7 TP8

### ISSUE THREAD

**Issue by VieraFederico** [marcelogarberoglio/PI#227]
Estimado Marcelo:

Estoy teniendo problemas con ejercicio 7 del Tp8, estoy usando todos los flags (incluido el -fstanitize) y estoy recibiendo un "exit code 1". No se exactamente donde me esta fallando el programa. Acá te dejo las funciones (el resto del programa es el testeo de la catedra): 

```
int chaseLimits(int x, int y, int dx, int dy,char sopa[FILS][COLS], char * s)
{
    int l=0, lim=strlen(s);
    for(int i=x,j=y;l<lim && (i>=0 && i<FILS) && (j>=0 && j<COLS);i+=dx,j+=dy,l++)
    {
        if(sopa[i][j]!=s[l])
            return 0;
    }
    if(l==lim-1)
        return 1;
    else return 0;
}
Tdireccion findDirection(int x, int y)
{
    if (x==0)
    {
        if(y==1)
            return DER;
        else
            return IZQ;
    }
    else if(x==1)
    {
        if(y==1)
            return D_AR;
        else if(y==0)
            return ARR;
        else
            return I_AR;
    }
    else
    {
        if(y==1)
            return D_AB;
        else if(y==0)
            return ABA;
        else
            return I_AB;
    }
}
void sorroundLetter(int x, int y, char * s,char sopa[FILS][COLS], struct posicion ** resp, int * p)
{
    for(int i=-1;i<=1;i++)
    {
        for(int j=-1;j<=1;j++)
        {
            if((x+i>0 && x+i<FILS) && (y+j>0 && y+j<COLS) && (sopa[x+i][y+j]==s[1]) && chaseLimits(x,y,i,j,sopa,s)==1)
            {
                if((*p)%BLOCK==0)
                    *resp = realloc(*resp, ((*p) + BLOCK) * sizeof(struct posicion));
                (*resp)[(*p)].palabra = malloc(strlen(s) + 1);
                strcpy((*resp)[(*p)].palabra,s);
                (*resp)[(*p)].fila=x;
                (*resp)[(*p)].columna=y;
                (*resp)[(*p)].direccion=findDirection(i,j);
                (*p)++;
            }
        }
    }
}
void wordSearch(char * s, struct posicion * resp, char sopa[FILS][COLS], int * p)
{
    for(int i=0;i<FILS;i++)
    {
        for(int j=0;j<COLS;j++)
        {
             if(sopa[i][j]==s[0])
                 sorroundLetter(i,j,s,sopa,&resp,p);
        }
    }
}

struct posicion * resolverSopa(char * diccionario[],char sopa[FILS][COLS])
{
    int p=0;
    struct posicion * resp = malloc(BLOCK * sizeof(struct posicion));
    for(int i=0;diccionario[i][0]!='\0';i++)
    {
        wordSearch(diccionario[i], resp, sopa,&p);
    }
    resp[p++].palabra=NULL;
    resp=realloc(resp,p*sizeof(struct posicion));
    return resp;
}
```

Muchas gracias por adelantado.

**Comment by marcelogarberoglio** [comment]
Copiá la salida que te da. Acordate de poner también el flag -g

**Comment by VieraFederico** [comment]
Estimado Marcelo:

Aca te dejo la salida completa del programa, intente poner printfs pero me sigue dando el exit code 1. El error me lo da con estos flags puestos: `set(CMAKE_C_FLAGS "-Wall -pedantic -std=c99 -lm -g -fsanitize=address")`. 

`C:\Windows\system32\wsl.exe --distribution Ubuntu --exec /bin/bash -c "export TSAN_OPTIONS='log_path='\"'\"'/mnt/c/Users/Intel/AppData/Local/Temp/clion-sanitizers66701152-584c-4a3e-8726-5bc15e32483b/b275cf5a-6b1d-45ac-9b4a-7289b4a2614a'\"'\"' stack_trace_format='\"'\"'pc_%p###func_%f###file_%s###line_%l###obj_%M'\"'\"' print_summary='\"'\"'true'\"'\"'' && export LSAN_OPTIONS='log_path='\"'\"'/mnt/c/Users/Intel/AppData/Local/Temp/clion-sanitizers66701152-584c-4a3e-8726-5bc15e32483b/b275cf5a-6b1d-45ac-9b4a-7289b4a2614a'\"'\"' stack_trace_format='\"'\"'pc_%p###func_%f###file_%s###line_%l###obj_%M'\"'\"' print_summary='\"'\"'true'\"'\"'' && export ASAN_OPTIONS='detect_stack_use_after_return=false log_path='\"'\"'/mnt/c/Users/Intel/AppData/Local/Temp/clion-sanitizers66701152-584c-4a3e-8726-5bc15e32483b/b275cf5a-6b1d-45ac-9b4a-7289b4a2614a'\"'\"' stack_trace_format='\"'\"'pc_%p###func_%f###file_%s###line_%l###obj_%M'\"'\"' print_summary='\"'\"'true'\"'\"'' && export TERM=xterm-256color && export MSAN_OPTIONS='log_path='\"'\"'/mnt/c/Users/Intel/AppData/Local/Temp/clion-sanitizers66701152-584c-4a3e-8726-5bc15e32483b/b275cf5a-6b1d-45ac-9b4a-7289b4a2614a'\"'\"' stack_trace_format='\"'\"'pc_%p###func_%f###file_%s###line_%l###obj_%M'\"'\"' print_summary='\"'\"'true'\"'\"'' && export UBSAN_OPTIONS='log_path='\"'\"'/mnt/c/Users/Intel/AppData/Local/Temp/clion-sanitizers66701152-584c-4a3e-8726-5bc15e32483b/b275cf5a-6b1d-45ac-9b4a-7289b4a2614a'\"'\"' stack_trace_format='\"'\"'pc_%p###func_%f###file_%s###line_%l###obj_%M'\"'\"' print_summary='\"'\"'true'\"'\"' print_stacktrace='\"'\"'1'\"'\"'' && cd '/mnt/c/Users/Intel/Desktop/ITBA/2023/Primer Cuatrimestre/72.31 - Programación Imperativa/Guias Resueltas/Guia 8/Ej 7/cmake-build-debug' && '/mnt/c/Users/Intel/Desktop/ITBA/2023/Primer Cuatrimestre/72.31 - Programación Imperativa/Guias Resueltas/Guia 8/Ej 7/cmake-build-debug/Ej_7'"

Process finished with exit code 1
`

**Comment by marcelogarberoglio** [comment]
No se a qué salida corresponde eso. Como dijiste que te fallaba con los flags, lo que tendrías que ver al ejecutar el programa es algo parecido a esto que copio abajo, que muestra el tipo de error y en qué línea ocurre. ¿Sin los flags también te falla?

=================================================================
==235624==ERROR: LeakSanitizer: detected memory leaks
 
Direct leak of 100 byte(s) in 1 object(s) allocated from:
    #0 0x4eaaa8 in __interceptor_malloc ../../.././libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x5283dd in main /users/PZS0710/edanish/test/asan/leak.c:6
    #2 0x2b0c29909544 in __libc_start_main (/lib64/libc.so.6+0x22544)

**Comment by VieraFederico** [comment]
No estoy seguro si es mi versión de WSL que falla pero no me aparece eso cuando uso los flags, me aparecen paredes de texto como la que mande antes. Recién lo probé sin los flags y recibo un "Exit code 11" si intento imprimir los contenidos de resp y "Exit Code 6" si borro el printf.

**Comment by marcelogarberoglio** [comment]
Fijate de probarlo en pampero.

**Comment by VieraFederico** [comment]
Todavía no puedo usar Pampero, yo me cambie a esta carrera desde Bioingeniería hace un año y aunque mande varios mails, no me crearon un usuario.
